name: PHP Laravel Package

on: [ push, pull_request ]

jobs:
  lint:
    name: Coding Standards (PHPCS)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Use PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHPCS
        run: composer phpcs

  testing:
    name: Test on PHP ${{ matrix.php }} with ${{ matrix.setup }} dependencies

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        setup: [ 'basic', 'lowest', 'stable' ]
        php: [ '8.4', '8.5' ]

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: forge
          POSTGRES_PASSWORD: forge
          POSTGRES_DB: forge
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - name: Use PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2 # Action page: <https://github.com/shivammathur/setup-php>
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_pgsql, pgsql
          coverage: none

      - name: Get Composer Cache Directory # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate composer.json
        run: composer validate

      - name: Install [LOWEST] Composer dependencies
        if: matrix.setup == 'lowest'
        run: composer update --prefer-dist --no-interaction --prefer-lowest

      - name: Install [BASIC] Composer dependencies
        if: matrix.setup == 'basic'
        run: composer update --prefer-dist --no-interaction

      - name: Install [STABLE] Composer dependencies
        if: matrix.setup == 'stable'
        run: composer update --prefer-dist --no-interaction --prefer-stable

      - name: Show most important packages' versions
        run: composer info | grep -e efureev -e laravel/framework -e phpunit/phpunit

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer test
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_DATABASE: forge
          DB_USERNAME: forge
          DB_PASSWORD: forge

  release:
    name: Create Release
    needs: [ testing ]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '.0') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
